# Generated by Django 5.0.7 on 2024-07-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=400)),
                ('message', models.CharField(blank=True, max_length=700)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
