# Generated by Django 5.0.7 on 2024-07-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndexApp', '0007_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='client/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
