# Generated by Django 5.0.7 on 2024-07-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IndexApp', '0011_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='locaton',
            new_name='road',
        ),
    ]
